apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      slack:
        token: <token>
        channel: <channel>
    resource:
      deployment:
       watch: true
       events:
        create: true
        update: false
        delete: true
      replicationcontroller:
       watch: true
       events:
        create: true
      replicaset:
       watch: true
       events:
        create: true
      daemonset:
       watch: true
       events:
        create: true
      services:
       watch: true
       events:
        create: true
        update: true
        loadbalancercreate: true
      pod:
       watch: true
       events:
        create: true
      secret:
       watch: true
       events:
        create: true
      configmap:
       watch: true
       events:
        create: true
